---
# NOTE: _fd_quiet_assert does not impact this task, as it first needs to be ensured that it actually is
#       properly defined
- name: 'assert | Ensure mandatory variables, as well as variables, which have a default value, are set (boolean)'
  ansible.builtin.assert:
    that:
      - "lookup('ansible.builtin.vars', __t_var) is defined"
      - "lookup('ansible.builtin.vars', __t_var) | bool | string == lookup('ansible.builtin.vars', __t_var) | string"
      - "lookup('ansible.builtin.vars', __t_var) is boolean"
    success_msg: "Variable '{{ __t_var }}' defined properly - value: '{{ lookup('ansible.builtin.vars', __t_var) }}'"
    fail_msg: "Variable '{{ __t_var }}' failed to validate"
  loop:
    - '_fd_quiet_assert'
  loop_control:
    loop_var: '__t_var'
    label: 'variable: {{ __t_var }}'

- name: 'assert | Ensure _fd_packages is defined properly'
  ansible.builtin.assert:
    that:
      # destination is defined for all items
      - >-
        _fd_files |
        selectattr('dest', 'undefined') |
        length == 0

      # owner is defined for all items
      - >-
        _fd_files |
        selectattr('owner', 'undefined') |
        length == 0

      # group is defined for all items
      - >-
        _fd_files |
        selectattr('group', 'undefined') |
        length == 0

      # mode is defined for all items
      - >-
        _fd_files |
        selectattr('mode', 'undefined') |
        length == 0

      # ensure all files that don't have a source defined, have content defined
      - >-
        _fd_files |
        rejectattr('src', 'defined') |
        selectattr('content', 'undefined') |
        length == 0

      # ensure all files that don't have content defined, have a source defined
      - >-
        _fd_files |
        rejectattr('content', 'defined') |
        selectattr('src', 'undefined') |
        length == 0

    success_msg: 'Files are defined correctly'
    fail_msg: 'One or more failed failed to validated correctly'
    quiet: '{{ _fd_quiet_assert }}'
...
