---
- name: 'file_deployment | Deploy file'
  ansible.builtin.copy:
    attributes: '{{ __t_file.attributes | default(omit) }}'
    backup: '{{ __t_file.backup | default(omit) }}'
    checksum: '{{ __t_file.checksum | default(omit) }}'
    content: '{{ __t_file.content | default(omit) }}'
    decrypt: '{{ __t_file.decrypt | default(omit) }}'
    dest: '{{ __t_file.dest }}'
    follow: '{{ __t_file.follow | default(omit) }}'
    directory_mode: '{{ __t_file.directory_mode | default(omit) }}'
    force: '{{ __t_file.force | default(omit) }}'
    group: '{{ __t_file.group }}'
    local_follow: '{{ __t_file.local_follow | default(false) }}'
    mode: '{{ __t_file.mode }}'
    owner: '{{ __t_file.owner }}'
    remote_src: '{{ __t_file.remote_source | default(omit) }}'
    selevel: '{{ __t_file.selevel | default(omit) }}'
    serole: '{{ __t_file.serole | default(omit) }}'
    setype: '{{ __t_file.setype | default(omit) }}'
    seuser: '{{ __t_file.seuser | default(omit) }}'
    src: '{{ __t_file.src | default(omit) }}'
    unsafe_writes: '{{ __t_file.unsafe_writes | default(omit) }}'
    validate: '{{ __t_file.validate | default(omit) }}'
  become: true
  loop: '{{ _fd_files }}'
  loop_control:
    loop_var: '__t_file'
    label: '{{ __t_file.dest }}'
...
