---
name: 'molecule'
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - 'main'
    paths:
      - '**'
      - '!.github/'
      - '.github/workflows/molecule.yml'

  push:
    branches:
      - 'main'
    paths:
      - '**'
      - '!.github/'
      - '.github/workflows/molecule.yml'

  workflow_dispatch:
    inputs:
      repoCache:
        description: 'Reset or disable the cache?'
        type: 'choice'
        default: 'enabled'
        options:
          - 'enabled'
          - 'disabled'
          - 'reset'

permissions:
  contents: 'read'

# Adding these as env variables makes it easy to re-use them in different steps and in bash.
env:
  cache_archive: 'molecule_cache.tar.gz'
  # This is the dir renovate provides
  # If we set our own directory via cacheDir, we can run into permissions issues.
  # It is also possible to cache a higher level of the directory, but it has minimal benefit. While renovate execution
  # time gets faster, it also takes longer to upload the cache as it grows bigger.
  cache_dir: '/tmp/.cache/molecule'
  # This can be manually changed to bust the cache if neccessary.
  cache_key: 'molecule-cache'

jobs:
  molecule:
    permissions:
      contents: 'write'
    runs-on: 'ubuntu-latest'
    container:
      image: '${{ matrix.container.image }}'
      credentials:
        username: '${{ secrets.crc_username }}'
        password: '${{ secrets.crc_password }}'
      options: '--privileged'
    strategy:
      matrix:
        container:
          #
          # UBI 8
          #

          # yamllint disable-line rule:line-length
          - image: 'registry.redhat.io/ansible-automation-platform/ee-minimal-rhel8:2.17.1@sha256:fa661580efb29a119489b71bc28e286a3f38bee89f312b756f3c0d4fd1df88c7'
            cache_key_suffix: 'rhel8-2.17'
            # renovate yaml: datasource=pypi
            molecule: '24.6.1'

          # yamllint disable-line rule:line-length
          - image: 'registry.redhat.io/ansible-automation-platform/ee-minimal-rhel8:2.16.8@sha256:22e6773b832d01602a6d822f8c947c79d46c6b932a466874776929adf39e7ed2'
            cache_key_suffix: 'rhel8-2.16'
            # renovate yaml: datasource=pypi
            molecule: '24.6.1'

          # yamllint disable-line rule:line-length
          - image: 'registry.redhat.io/ansible-automation-platform/ee-minimal-rhel8:2.15.11@sha256:0cda496e21c9565b00ba7e2da8c4f85e56dbdcf7a22f07749e4177ec5c106186'
            cache_key_suffix: 'rhel8-2.15'
            # renovate yaml: datasource=pypi
            molecule: '6.0.3'

          # yamllint disable-line rule:line-length
          - image: 'registry.redhat.io/ansible-automation-platform/ee-minimal-rhel8:2.14.13@sha256:8ae958de1fa41427b7fc972d96f5b97ff6e3d878de1dceba9de6bfd2377fb990'
            cache_key_suffix: 'rhel8-2.14'
            # renovate yaml: datasource=pypi
            molecule: '6.0.3'

          # yamllint disable-line rule:line-length
          - image: 'registry.redhat.io/ansible-automation-platform/ee-minimal-rhel8:2.13.10@sha256:6d7db6eebd6653c20c0e4dd93e51190001431d2183bd5435834664d39311876f'
            cache_key_suffix: 'rhel8-2.13'
            # renovate yaml: datasource=pypi
            molecule: '6.0.3'

          #
          # UBI 9
          #

          # yamllint disable-line rule:line-length
          - image: 'registry.redhat.io/ansible-automation-platform/ee-minimal-rhel9:2.17.1@sha256:396cd568af193191dca7d1ba059cfd5c5f98e20b2e96c16e2b5e4559c5178e8e'
            cache_key_suffix: 'rhel9-2.17'
            # renovate yaml: datasource=pypi
            molecule: '24.6.1'
            additional_packages:
              - 'python-unversioned-command'

          # yamllint disable-line rule:line-length
          - image: 'registry.redhat.io/ansible-automation-platform/ee-minimal-rhel9:2.16.7@sha256:d85db31e680adb29782aa10d44bf8e9e169a3c3df41d53b1162a325840442625'
            cache_key_suffix: 'rhel9-2.16'
            # renovate yaml: datasource=pypi
            molecule: '24.6.1'
            additional_packages:
              - 'python-unversioned-command'

          # yamllint disable-line rule:line-length
          - image: 'registry.redhat.io/ansible-automation-platform/ee-minimal-rhel9:2.15.11@sha256:3134d816655b0f4bb072cb0cd27ac7217ee8e2f0ec0f5569db1bbdd8d9a25bb8'
            cache_key_suffix: 'rhel9-2.15'
            # renovate yaml: datasource=pypi
            molecule: '6.0.3'
            additional_packages:
              - 'python-unversioned-command'

    steps:
      - name: 'Install NodeJS and podman'
        run: 'microdnf install nodejs podman -y'

      - name: 'Checkout repository'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # v4.1.7

      - name: 'Download cache of the previous workflow run'
        uses: 'dawidd6/action-download-artifact@bf251b5aa9c2f7eeb574a96ee720e24f801b7c11' # v6
        if: "github.event.inputs.repoCache != 'disabled'"
        continue-on-error: true
        with:
          name: '${{ env.cache_key }}-${{ matrix.container.cache_key_suffix }}'
          path: 'cache-download'

      - name: 'Extract molecule cache to improve performance'
        if: "github.event.inputs.repoCache != 'disabled'"
        run: |
          set -x
          # Skip if no cache is set, such as the first time it runs.
          if [ ! -d cache-download ] ; then
            echo "No cache found."
            exit 0
          fi

          # Make sure the directory exists, and extract it there. Note that it's nested in the download directory.
          mkdir -p "${cache_dir}"
          tar -xzf "cache-download/${cache_archive}" -C "${cache_dir}"

      - name: 'Install additional packages'
        if: "join(matrix.container.additional_packages, ' ') != ''"
        run: |
          microdnf install -y ${{ join(matrix.container.additional_packages, ' ') }}

      - name: 'Install Python packages'
        run: |
          pip3 install molecule==${{ matrix.container.molecule }}
          mkdir -pv "${cache_dir}"

      - name: 'Run molecule'
        run: |
          molecule test

      - name: 'Compress molecule cache to improve performance'
        if: "github.event.inputs.repoCache != 'disabled'"
        run: |
          # The -C is important, as otherwise we end up extracting the files with
          # their full path, ultimately leading to a nested directory situation.
          tar -czf "${cache_archive}" -C "${cache_dir}" .

      - name: 'Upload compressed cache'
        uses: 'actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b' # v4.3.4
        if: "github.event.inputs.repoCache != 'disabled'"
        with:
          name: '${{ env.cache_key }}-${{ matrix.container.cache_key_suffix }}'
          path: '${{ env.cache_archive }}'
          # Since this is updated and restored on every run, we don't need to keep it
          # for long. Just make sure this value is large enough that multiple renovate
          # runs can happen before older cache archives are deleted.
          retention-days: 1
...
