---
name: 'pre-commit'
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - 'main'

  push:
    branches:
      - 'main'

  workflow_dispatch:
    inputs:
      repoCache:
        description: 'Reset or disable the cache?'
        type: 'choice'
        default: 'enabled'
        options:
          - 'enabled'
          - 'disabled'
          - 'reset'

permissions:
  contents: 'read'

# Adding these as env variables makes it easy to re-use them in different steps and in bash.
env:
  cache_archive: 'pre-commit_cache.tar.gz'
  # This is the dir renovate provides
  # If we set our own directory via cacheDir, we can run into permissions issues.
  # It is also possible to cache a higher level of the directory, but it has minimal benefit. While renovate execution
  # time gets faster, it also takes longer to upload the cache as it grows bigger.
  cache_dir: '/tmp/.cache/pre-commit'
  # This can be manually changed to bust the cache if neccessary.
  cache_key: 'pre-commit-cache'
  # File that contains the pre-commit hooks to skip
  hook_skip_file: './.github/.pre-commit-skip-hooks'

jobs:
  pre-commit:
    permissions:
      contents: 'write'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Harden Runner'
        uses: 'step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6' # v2.8.1
        with:
          egress-policy: 'audit'

      - name: 'Checkout repository'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # v4.1.7

      - name: 'Download cache of the previous workflow run'
        uses: 'dawidd6/action-download-artifact@bf251b5aa9c2f7eeb574a96ee720e24f801b7c11' # v6
        if: "github.event.inputs.repoCache != 'disabled'"
        continue-on-error: true
        with:
          name: '${{ env.cache_key }}'
          path: 'cache-download'

      - name: 'Extract pre-commit cache to improve performance'
        run: |
          set -x
          # Skip if no cache is set, such as the first time it runs.
          if [ ! -d cache-download ] ; then
            echo "No cache found."
            exit 0
          fi

          # Make sure the directory exists, and extract it there. Note that it's nested in the download directory.
          mkdir -p "${cache_dir}"
          tar -xzf "cache-download/${cache_archive}" -C "${cache_dir}"

          # Unfortunately, the permissions expected within renovate's docker container
          # are different than the ones given after the cache is restored. We have to
          # change ownership to solve this. We also need to have correct permissions in
          # the entire /tmp/renovate tree, not just the section with the repo cache.
          ls -R "${cache_dir}"

      - name: 'Install aspell'
        run: 'sudo apt-get update && sudo apt-get install -y aspell aspell-en'

      - name: 'Install Python'
        uses: 'actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d' # v5.1.0
        with:
          python-version: '3.11'

      - name: 'Install pre-commit'
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pre-commit
          mkdir -pv "${cache_dir}"

      - name: 'Run pre-commit'
        run: |
          set -x
          export PRE_COMMIT_HOME="${cache_dir}"
          if [[ -f "${hook_skip_file}" ]]; then
            export SKIP="$(tr '\n' ',' < "${hook_skip_file}")"
            echo "${SKIP}"
          fi
          env
          ls -la "${PRE_COMMIT_HOME}" || true
          pre-commit run --verbose --all-files --show-diff-on-failure

      - name: 'Compress pre-commit cache to improve performance'
        run: |
          ls "${cache_dir}"
          # The -C is important, as otherwise we end up extracting the files with
          # their full path, ultimately leading to a nested directory situation.
          tar -czvf "${cache_archive}" -C "${cache_dir}" .

      - name: 'Upload compressed cache'
        uses: 'actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808' # v4.3.3
        if: "github.event.inputs.repoCache != 'disabled'"
        with:
          name: '${{ env.cache_key }}'
          path: '${{ env.cache_archive }}'
          # Since this is updated and restored on every run, we don't need to keep it
          # for long. Just make sure this value is large enough that multiple renovate
          # runs can happen before older cache archives are deleted.
          retention-days: 1
...
