---
name: 'Publish to Ansible Galaxy'
on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch: {}

jobs:
  build:
    name: 'Publish to Ansible Galaxy'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'checkout'
        uses: 'actions/checkout@v4'
        if: >-
          github.ref == 'refs/heads/main'

      - name: 'galaxy'
        uses: 'robertdebock/galaxy-action@1.2.0'
        if: >-
          github.ref == 'refs/heads/main'
        with:
          galaxy_api_key: '${{ secrets.galaxy_api_key }}'
          git_branch: 'main'

      - name: 'Create a new release on GitHub'
        uses: 'softprops/action-gh-release@v2'
        if: >-
          github.ref == 'refs/heads/main'
        with:
          draft: false
          prerelease: false
          token: '${{ github.token }}'
          discussion_category_name: 'Release'
          generate_release_notes: true
          make_latest: true
...
